version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - order-service
      - inventory-service
      - notification-service

  order-service:
    build: ./backend/order-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORACLE_URL=jdbc:oracle:thin:@oracle:1521:RTOPS
    depends_on:
      - kafka
      - oracle

  inventory-service:
    build: ./backend/inventory-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORACLE_URL=jdbc:oracle:thin:@oracle:1521:RTOPS
    depends_on:
      - kafka
      - oracle

  notification-service:
    build: ./backend/notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  oracle:
    image: container-registry.oracle.com/database/enterprise:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=rtops123
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: