apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: rtops
build:
  artifacts:
    - image: rtops/frontend
      context: .
      docker:
        dockerfile: Dockerfile.frontend
    - image: rtops/backend
      context: .
      docker:
        dockerfile: Dockerfile.backend
deploy:
  kubectl:
    manifests:
      - k8s/base/*.yaml