server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  scrape_configs:
    - job_name: 'spring-actuator'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['backend:8080']
    
    - job_name: 'kafka'
      static_configs:
        - targets: ['kafka-exporter:9308']