name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build Backend
        run: |
          cd backend
          mvn clean package

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Run Tests
        run: |
          cd backend
          mvn test
          cd ../frontend
          npm test

      - name: Build and Push Docker Images
        if: github.ref == 'refs/heads/main'
        run: |
          docker-compose build
          docker-compose push
